<a href="https://colab.research.google.com/github/tonpiplaifa/data_viz/blob/main/Pandas102.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os

In [ ]:
path = '/content/drive/My Drive/Data_viz'

In [ ]:
covid_file_path = os.path.join(path,'pm-18-jan-2021.csv')
print(covid_file_path) #ดีที่ os รันที่ไหนเชื่อมแบบนั้นให้ทันที

/content/drive/My Drive/Data_viz/pm-18-jan-2021.csv


In [ ]:
a = path + '/pm-18-jan-2021.csv'
print(a)

/content/drive/My Drive/Data_viz/pm-18-jan-2021.csv


In [ ]:
data_covid = pd.read_csv(covid_file_path)
data_covid.head()

No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[5 rows x 10 columns]

##isnull() None?
ที่เค้าไปเชคจะต้องเป็น array

In [ ]:
data_covid.isnull()

No.  announce_date  ...  district_of_onset   risk
0      False          False  ...               True  False
1      False          False  ...               True  False
2      False          False  ...              False  False
3      False          False  ...               True  False
4      False          False  ...               True  False
...      ...            ...  ...                ...    ...
12418  False          False  ...              False  False
12419  False          False  ...              False  False
12420  False          False  ...              False  False
12421  False          False  ...              False  False
12422  False          False  ...              False  False

[12423 rows x 10 columns]

any() เอาค่าความจริงภายในแต่ละ column มา OR กัน True คือมีค่าว่างอยู่ในคอลัม

In [ ]:
data_covid.isnull().any()

No.                      False
announce_date            False
notification_date         True
sex                       True
age                       True
nationality               True
province_of_isolation     True
province_of_onset         True
district_of_onset         True
risk                      True
dtype: bool

all() เอาค่าความจริงภายในแต่ละ column มา AND กัน มีเท็จนิดเดียวก็ว่างเลย

In [ ]:
data_covid.isnull().all()

No.                      False
announce_date            False
notification_date        False
sex                      False
age                      False
nationality              False
province_of_isolation    False
province_of_onset        False
district_of_onset        False
risk                     False
dtype: bool

####Tip

In [ ]:
data_covid.iloc[0,0].isnull() #จะต้องเป็น array

AttributeError: ignored

In [ ]:
data_covid.iloc[0,0]

1

In [ ]:
data_covid.iloc[:1,0].isnull() #ใช้ดารตัดตาราง เมื่อจะใช้ isnull() ในการเชคค่าว่าง

0    False
Name: No., dtype: bool

## ต่อตารางแกน X แกน y
- ต่อแกน y คือเพิ่ม record (เพิ่มจำนวนข้อมูล)
- ต่อแกน x คือเพิ่ม column (เพิ่มรายละเอียดข้อมูล)


####ต่อแกน y pd.concat

In [ ]:
data_covid['province_of_onset']=='ขอนแก่น'

0        False
1        False
2        False
3        False
4        False
         ...  
12418    False
12419    False
12420    False
12421    False
12422    False
Name: province_of_onset, Length: 12423, dtype: bool

In [ ]:
dataKK = data_covid[data_covid['province_of_onset']=='ขอนแก่น']
dataKK.head()

No.  ...                                           risk
180    181  ...                                        สนามมวย
462    463  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1466  1467  ...                  คนไทยเดินทางกลับจากต่างประเทศ
1970  1971  ...  ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
2637  2638  ...                  สัมผัสผู้เดินทางจากต่างประเทศ

[5 rows x 10 columns]

In [ ]:
dataUD = data_covid[data_covid['province_of_onset']=='อุดรธานี']
dataUD.head()

No.  ...                                         risk
424  425  ...                                      สนามมวย
434  435  ...                                  สถานบันเทิง
471  472  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
883  884  ...                                  สถานบันเทิง
885  886  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[5 rows x 10 columns]

In [ ]:
dataMS = data_covid[data_covid['province_of_onset']=='มหาสารคาม']
dataMS.head()

No.  ...                                         risk
346      347  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
789      790  ...                                  สถานบันเทิง
6690    6691  ...                            Cluster สมุทรสาคร
10802  10803  ...                            Cluster สมุทรสาคร

[4 rows x 10 columns]

In [ ]:
dataMYisan = pd.concat([dataKK,dataUD,dataMS])
dataMYisan

No.  ...                                           risk
180      181  ...                                        สนามมวย
462      463  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1466    1467  ...                  คนไทยเดินทางกลับจากต่างประเทศ
1970    1971  ...  ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
2637    2638  ...                  สัมผัสผู้เดินทางจากต่างประเทศ
2673    2674  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
5948    5949  ...                              Cluster สมุทรสาคร
6082    6083  ...                              Cluster สมุทรสาคร
9333    9334  ...                           อยู่ระหว่างการสอบสวน
9334    9335  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
10610  10611  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11517  11518  ...                           อยู่ระหว่างการสอบสวน
11697  11698  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11698  11699  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
424      425  ...                                        สนามมวย
434      435  ...                                    สถานบันเทิง
471      472  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
883      884  ...                                    สถานบันเทิง
885      886  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
941      942  ...                                    สถานบันเทิง
1059    1060  ...                  คนไทยเดินทางกลับจากต่างประเทศ
2013    2014  ...                  คนไทยเดินทางกลับจากต่างประเทศ
5810    5811  ...                              Cluster สมุทรสาคร
7433    7434  ...                                  Cluster ระยอง
346      347  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
789      790  ...                                    สถานบันเทิง
6690    6691  ...                              Cluster สมุทรสาคร
10802  10803  ...                              Cluster สมุทรสาคร

[28 rows x 10 columns]

####ต่อแกน x
- จับ 2 ตารางมาต่อกันเลย (merge)
- เลือกเฉพาะบางคอลัมที่เราต้องการ (map)

In [ ]:
data_province = data_covid[['No.','announce_date','province_of_onset']]
data_province

No. announce_date province_of_onset
0          1     1/12/2020     กรุงเทพมหานคร
1          2     1/17/2020     กรุงเทพมหานคร
2          3     1/22/2020            นครปฐม
3          4     1/22/2020     กรุงเทพมหานคร
4          5     1/24/2020     กรุงเทพมหานคร
...      ...           ...               ...
12418  12419     1/18/2021       สมุทรปราการ
12419  12420     1/18/2021       สมุทรปราการ
12420  12421     1/18/2021            ชลบุรี
12421  12422     1/18/2021            ชลบุรี
12422  12423     1/18/2021             ระยอง

[12423 rows x 3 columns]

In [ ]:
data_human = data_covid[['No.','age','sex','nationality']]
data_human

No.   age   sex nationality
0          1  61.0  หญิง       China
1          2  74.0  หญิง       China
2          3  73.0  หญิง    Thailand
3          4  68.0   ชาย       China
4          5  66.0  หญิง       China
...      ...   ...   ...         ...
12418  12419  28.0  หญิง    Thailand
12419  12420  27.0  หญิง    Thailand
12420  12421  10.0   ชาย    Thailand
12421  12422  52.0   ชาย    Thailand
12422  12423  51.0   ชาย    Thailand

[12423 rows x 4 columns]

# แบบง่าย รู้ว่าสองตาราง record ตรงกัน

In [ ]:
full_table1 = data_human.merge(data_province)
full_table1.head() #จับ 2 ตารางมาต่อกันเลย แบบง่าย รู้อยู่แล้วว่าสองตารางมี record ตรงกันจึงไม่กำหนด key ที่ต้องเชื่อมกัน

No.   age   sex nationality announce_date province_of_onset
0    1  61.0  หญิง       China     1/12/2020     กรุงเทพมหานคร
1    2  74.0  หญิง       China     1/17/2020     กรุงเทพมหานคร
2    3  73.0  หญิง    Thailand     1/22/2020            นครปฐม
3    4  68.0   ชาย       China     1/22/2020     กรุงเทพมหานคร
4    5  66.0  หญิง       China     1/24/2020     กรุงเทพมหานคร

## sort

In [ ]:
data_human2 = data_human.sort_values('age')
data_human2

No.   age   sex nationality
1987    1988  0.10   ชาย    Thailand
6477    6478  0.11  หญิง    Thailand
11497  11498  0.11   ชาย       Burma
1675    1676  0.30   ชาย       Japan
1075    1076  0.40   ชาย    Thailand
...      ...   ...   ...         ...
12405  12406   NaN   NaN         NaN
12406  12407   NaN   NaN         NaN
12407  12408   NaN   NaN         NaN
12408  12409   NaN   NaN         NaN
12409  12410   NaN   NaN         NaN

[12423 rows x 4 columns]

In [ ]:
full_table2 = data_human2.merge(data_province)
full_table2.head()

No.   age   sex nationality announce_date province_of_onset
0   1988  0.10   ชาย    Thailand      4/4/2020             ระยอง
1   6478  0.11  หญิง    Thailand    12/30/2020          เพชรบุรี
2  11498  0.11   ชาย       Burma     1/16/2021         สมุทรสาคร
3   1676  0.30   ชาย       Japan      4/1/2020     กรุงเทพมหานคร
4   1076  0.40   ชาย    Thailand     3/27/2020      สุราษฎร์ธานี

In [ ]:
data_human2_renamed = data_human2.rename(columns={'No.':'patientNumber'})
data_human2_renamed.head()

patientNumber   age   sex nationality
1987            1988  0.10   ชาย    Thailand
6477            6478  0.11  หญิง    Thailand
11497          11498  0.11   ชาย       Burma
1675            1676  0.30   ชาย       Japan
1075            1076  0.40   ชาย    Thailand

In [ ]:
data_human2_renamed.merge(data_province) #เนื่องจากไม่มีชื่อคอลัมที่เหมือนกันเลย

MergeError: ignored

In [ ]:
full_table3 = data_human2_renamed.merge(data_province,left_on='patientNumber',right_on='No.') #กำหนดคีย์ที่ใส่เชื่อมกันของสองตาราง
full_table3.head()

patientNumber   age   sex nationality    No. announce_date province_of_onset
0           1988  0.10   ชาย    Thailand   1988      4/4/2020             ระยอง
1           6478  0.11  หญิง    Thailand   6478    12/30/2020          เพชรบุรี
2          11498  0.11   ชาย       Burma  11498     1/16/2021         สมุทรสาคร
3           1676  0.30   ชาย       Japan   1676      4/1/2020     กรุงเทพมหานคร
4           1076  0.40   ชาย    Thailand   1076     3/27/2020      สุราษฎร์ธานี

In [ ]:
full_table3_1 = data_human2_renamed.merge(data_covid,how='left',left_on='age',right_on='age')
full_table3_1.head()

patientNumber  ...                                         risk
0           1988  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1           6478  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
2           6478  ...                            Cluster สมุทรสาคร
3          11498  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
4          11498  ...                            Cluster สมุทรสาคร

[5 rows x 13 columns]

####map()

In [ ]:
data_human2_renamed.head()

patientNumber   age  ... num                                       detail
1987            1988  0.10  ...   0  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
6477            6478  0.11  ...   1  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11497          11498  0.11  ...   2                            Cluster สมุทรสาคร
1675            1676  0.30  ...   3  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1075            1076  0.40  ...   4  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[5 rows x 6 columns]

In [ ]:
data_covid.head()

No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[5 rows x 10 columns]

**คุณสมบัติของ pandas ก็คือเราสามารถสร้าง column ใหม่ให้ตาราง df ได้ โดย**

```df['ชื่อ column ใหม่'] = (list ที่มีจำนวนสมาชิกเท่ากับจำนวน record ของ df)```

In [ ]:
data_human2_renamed.head()

patientNumber   age  ... num                                       detail
1987            1988  0.10  ...   0  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
6477            6478  0.11  ...   1  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11497          11498  0.11  ...   2                            Cluster สมุทรสาคร
1675            1676  0.30  ...   3  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1075            1076  0.40  ...   4  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[5 rows x 6 columns]

In [ ]:
data_human2_renamed['num'] = range(data_human2_renamed.shape[0])
data_human2_renamed

patientNumber   age  ...    num                                       detail
1987            1988  0.10  ...      0  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
6477            6478  0.11  ...      1  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11497          11498  0.11  ...      2                            Cluster สมุทรสาคร
1675            1676  0.30  ...      3  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1075            1076  0.40  ...      4  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
...              ...   ...  ...    ...                                          ...
12405          12406   NaN  ...  12418                            Cluster สมุทรสาคร
12406          12407   NaN  ...  12419                            Cluster สมุทรสาคร
12407          12408   NaN  ...  12420                            Cluster สมุทรสาคร
12408          12409   NaN  ...  12421                            Cluster สมุทรสาคร
12409          12410   NaN  ...  12422                            Cluster สมุทรสาคร

[12423 rows x 6 columns]

In [ ]:
data_human2_renamed['patientNumber'].map(data_covid.set_index('No.')['risk']) #.map มันจะ ผูกค่า 'patientNumber' กับ 'No.' เข้าด้วยกัน แล้ว return list ของค่า ['risk']

1987     สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
6477     สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11497                              Cluster สมุทรสาคร
1675     สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1075     สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
                            ...                     
12405                              Cluster สมุทรสาคร
12406                              Cluster สมุทรสาคร
12407                              Cluster สมุทรสาคร
12408                              Cluster สมุทรสาคร
12409                              Cluster สมุทรสาคร
Name: patientNumber, Length: 12423, dtype: object

In [ ]:
data_human2_renamed['detail'] = data_human2_renamed['patientNumber'].map(data_covid.set_index('No.')['risk'])
data_human2_renamed

patientNumber   age  ...    num                                       detail
1987            1988  0.10  ...      0  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
6477            6478  0.11  ...      1  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11497          11498  0.11  ...      2                            Cluster สมุทรสาคร
1675            1676  0.30  ...      3  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1075            1076  0.40  ...      4  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
...              ...   ...  ...    ...                                          ...
12405          12406   NaN  ...  12418                            Cluster สมุทรสาคร
12406          12407   NaN  ...  12419                            Cluster สมุทรสาคร
12407          12408   NaN  ...  12420                            Cluster สมุทรสาคร
12408          12409   NaN  ...  12421                            Cluster สมุทรสาคร
12409          12410   NaN  ...  12422                            Cluster สมุทรสาคร

[12423 rows x 6 columns]

##HW7 สร้างตารางใหม่ ที่ค่าใน sex เป็น missing ทั้งหมด
- สรุปว่าทำไม record นั้นๆถึงเป็น missing ใช้การดู นับ อื่นๆ

In [45]:
data_covid.head()

No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[5 rows x 10 columns]

In [47]:
data_covid.isnull().any()

No.                      False
announce_date            False
notification_date         True
sex                       True
age                       True
nationality               True
province_of_isolation     True
province_of_onset         True
district_of_onset         True
risk                      True
dtype: bool

In [50]:
sex_fill = data_covid.fillna(value={'sex':'ไม่รู้'})
sex_fill.head()

No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[5 rows x 10 columns]

In [53]:
sex_missing = sex_fill[sex_fill['sex']=='ไม่รู้']
sex_missing

No. announce_date  ... district_of_onset               risk
4391    4392    12/20/2020  ...             เมือง  Cluster สมุทรสาคร
4392    4393    12/20/2020  ...             เมือง  Cluster สมุทรสาคร
4393    4394    12/20/2020  ...             เมือง  Cluster สมุทรสาคร
4394    4395    12/20/2020  ...             เมือง  Cluster สมุทรสาคร
4395    4396    12/20/2020  ...             เมือง  Cluster สมุทรสาคร
...      ...           ...  ...               ...                ...
12405  12406     1/18/2021  ...               NaN  Cluster สมุทรสาคร
12406  12407     1/18/2021  ...               NaN  Cluster สมุทรสาคร
12407  12408     1/18/2021  ...               NaN  Cluster สมุทรสาคร
12408  12409     1/18/2021  ...               NaN  Cluster สมุทรสาคร
12409  12410     1/18/2021  ...               NaN  Cluster สมุทรสาคร

[2497 rows x 10 columns]

In [54]:
sex_missing.shape #มีจำนวนเรคคอร์ดที่ไม่ได้ระบุเพศไว้อยู่ 2497 ราย

(2497, 10)

In [60]:
sex_missing[sex_missing['nationality']=='Burma'].shape
#เป็นผู้ป่วยสัญชาติเมียนมา 1366 รายจากผู้ป่วยทั้งหมดที่ไม่รู้เพศ

(1366, 10)

In [57]:
sex_missing[sex_missing['province_of_onset']=='สมุทรสาคร'].shape 
#เป็นผู้ป่วยพบในจังหวัดสมุทรสาครถึง 1353 รายจากผู้ป่วยทั้งหมดที่ไม่รู้เพศ

(1353, 10)

In [62]:
ss_sex_missing = sex_missing[sex_missing['province_of_onset']=='สมุทรสาคร']
ss_sex_missing.head()

No. announce_date  ... district_of_onset               risk
4391  4392    12/20/2020  ...             เมือง  Cluster สมุทรสาคร
4392  4393    12/20/2020  ...             เมือง  Cluster สมุทรสาคร
4393  4394    12/20/2020  ...             เมือง  Cluster สมุทรสาคร
4394  4395    12/20/2020  ...             เมือง  Cluster สมุทรสาคร
4395  4396    12/20/2020  ...             เมือง  Cluster สมุทรสาคร

[5 rows x 10 columns]

In [64]:
ss_sex_missing[ss_sex_missing['nationality']=='Burma'].shape
#จากผู้ป่วยทั้งหมดที่ไม่รู้เพศพบที่ในจังหวัดสมุทรสาคร 1353 ราย และพบว่าเป็นผู้ป่วยสัญชาติเมียนมา 1349 ราย

(1349, 10)

**สรุป**
- จากการวิเคราะห์พบว่ามีผู้ป่วยที่ไม่ทราบเพศถึง 2497 ราย จากทั้งประเทศไทย ณ 18/1/2564
- เมื่อสังเกตและค้นดูพบว่าเป็นผู้ป่วยพบในจังหวัดสมุทรสาครถึง 1353 ราย จากผู้ป่วยทั้งหมดที่ไม่รู้เพศ
- และพบว่าเป็นผู้ป่วยสัญชาติเมียนมา 1349 ราย จากผู้ป่วยทั้งหมดที่ไม่รู้เพศที่พบในจังหวัดสมุทรสาคร
- ที่เกิด missing ในคอลัมเพศเกิดขึ้นอจจะเป็นเพราะสถานการณ์ในจังหวัดสาครที่พบผู้ป่วยจำนวนมาก และยังมีสัญชาติเมียนมาจำนวนมากทำให้ต้องเร่งในการกักตัว จนอาจจะไม่รอบคอบจนเกิด missing นี้